version: '3.7'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sicoop_bd
      MYSQL_USER: sicoop
      MYSQL_PASSWORD: sicoop
    ports:
      - "3309:3309"
    volumes:
      - ./data:/home/jovyan/work/data
      - ./sh_init:/home/jovyan/work/sh
    command:
      sh /home/jovyan/work/sh/sql_init.sh
    networks:
      - mysql-net

  spark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./jars:/home/jovyan/work/jars
      - ./spark_script:/home/jovyan/work/scripts/
      - ./sh_init:/home/jovyan/work/sh
    command:
      sh /home/jovyan/work/sh/spark.sh
    depends_on:
      - mysql
    networks:
      - mysql-net
    links:
      - mysql:mysql

networks:
  mysql-net:
    driver: bridge