version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sicoop_bd
      MYSQL_USER: sicoop
      MYSQL_PASSWORD: sicoop
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysqld.sock:/var/run/mysqld/mysqld.sock
      - mysql-data:/var/lib/mysql
      - ./data/gerar_tabelas_bd.sql:/docker-entrypoint-initdb.d/gerar_tabelas.sql
    networks:
      - mysql-net

  spark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./jars:/home/jovyan/work/jars
      - ./spark_script:/home/jovyan/work/spark_script/
      - ./sh_init:/home/jovyan/work/sh_init
    command:
      sh /home/jovyan/work/sh_init/spark.sh
    depends_on:
      - mysql
    networks:
      - mysql-net

networks:
  mysql-net:
    driver: bridge

volumes:
  mysql-data: