version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sicoop_bd
      MYSQL_USER: sicoop
      MYSQL_PASSWORD: sicoop
      MYSQL_HOST: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/gerar_tabelas_bd.sql:/docker-entrypoint-initdb.d/gerar_tabelas.sql
    networks:
      - mysql-net

  spark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./jars:/home/jovyan/work/jars
      - ./spark_script:/home/jovyan/work/scripts/
      - ./sh_init:/home/jovyan/work/sh
    command:
      sh /home/jovyan/work/sh/spark.sh
    depends_on:
      - mysql
    networks:
      - mysql-net
    links:
      - mysql:mysql

networks:
  mysql-net:
    driver: bridge